<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Created by GNU Texinfo 6.6, http://www.gnu.org/software/texinfo/ -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Handling Errors Using Do-Catch (The Swift Programming Language Guide (Swift 5.1))</title>

<meta name="description" content="Handling Errors Using Do-Catch (The Swift Programming Language Guide (Swift 5.1))">
<meta name="keywords" content="Handling Errors Using Do-Catch (The Swift Programming Language Guide (Swift 5.1))">
<meta name="resource-type" content="document">
<meta name="distribution" content="global">
<meta name="Generator" content="makeinfo">
<link href="index.html#Top" rel="start" title="Top">
<link href="Index.html#Index" rel="index" title="Index">
<link href="index.html#SEC_Contents" rel="contents" title="Table of Contents">
<link href="Handling-Errors.html#Handling-Errors" rel="up" title="Handling Errors">
<link href="Converting-Errors-to-Optional-Values.html#Converting-Errors-to-Optional-Values" rel="next" title="Converting Errors to Optional Values">
<link href="Propagating-Errors-Using-Throwing-Functions.html#Propagating-Errors-Using-Throwing-Functions" rel="prev" title="Propagating Errors Using Throwing Functions">
<style type="text/css">
<!--
a.summary-letter {text-decoration: none}
blockquote.indentedblock {margin-right: 0em}
div.display {margin-left: 3.2em}
div.example {margin-left: 3.2em}
div.lisp {margin-left: 3.2em}
kbd {font-style: oblique}
pre.display {font-family: inherit}
pre.format {font-family: inherit}
pre.menu-comment {font-family: serif}
pre.menu-preformatted {font-family: serif}
span.nolinebreak {white-space: nowrap}
span.roman {font-family: initial; font-weight: normal}
span.sansserif {font-family: sans-serif; font-weight: normal}
ul.no-bullet {list-style: none}
-->
</style>
<link rel="stylesheet" type="text/css" href="https://gnu.org/software/emacs/manual.css">


</head>

<body lang="en">
<span id="Handling-Errors-Using-Do_002dCatch"></span><div class="header">
<p>
Next: <a href="Converting-Errors-to-Optional-Values.html#Converting-Errors-to-Optional-Values" accesskey="n" rel="next">Converting Errors to Optional Values</a>, Previous: <a href="Propagating-Errors-Using-Throwing-Functions.html#Propagating-Errors-Using-Throwing-Functions" accesskey="p" rel="prev">Propagating Errors Using Throwing Functions</a>, Up: <a href="Handling-Errors.html#Handling-Errors" accesskey="u" rel="up">Handling Errors</a> &nbsp; [<a href="index.html#SEC_Contents" title="Table of contents" rel="contents">Contents</a>][<a href="Index.html#Index" title="Index" rel="index">Index</a>]</p>
</div>
<hr>
<span id="Handling-Errors-Using-Do_002dCatch-1"></span><h4 class="subsection">22.2.2 Handling Errors Using Do-Catch</h4>

<span id="index-do"></span>
<span id="index-catch"></span>

<p>You use a &lsquo;<samp>do</samp>&rsquo;-&lsquo;<samp>catch</samp>&rsquo; statement to handle errors by running a block of
code. If an error is thrown by the code in the &lsquo;<samp>do</samp>&rsquo; clause, it is
matched against the &lsquo;<samp>catch</samp>&rsquo; clauses to determine which one of them can
handle the error.
</p>
<p>Here is the general form of a &lsquo;<samp>do</samp>&rsquo;-&lsquo;<samp>catch</samp>&rsquo; statement:
</p>
<div class="example">
<pre class="example">do {
    try expression
    statements
} catch pattern 1 {
    statements
} catch pattern 2 where condition {
    statements
} catch {
    statements
}
</pre></div>

<p>You write a pattern after &lsquo;<samp>catch</samp>&rsquo; to indicate what errors that clause
can handle. If a &lsquo;<samp>catch</samp>&rsquo; clause doesn&rsquo;t have a pattern, the clause
matches any error and binds the error to a local constant named &lsquo;<samp>error</samp>&rsquo;.
For more information about pattern matching, see Patterns.
</p>
<p>For example, the following code matches against all three cases of the
&lsquo;<samp>VendingMachineError</samp>&rsquo; enumeration.
</p>
<div class="example">
<pre class="example">var vendingMachine = VendingMachine()
vendingMachine.coinsDeposited = 8
do {
    try buyFavoriteSnack(person: &quot;Alice&quot;, vendingMachine: vendingMachine)
    print(&quot;Success! Yum.&quot;)
} catch VendingMachineError.invalidSelection {
    print(&quot;Invalid Selection.&quot;)
} catch VendingMachineError.outOfStock {
    print(&quot;Out of Stock.&quot;)
} catch VendingMachineError.insufficientFunds(let coinsNeeded) {
    print(&quot;Insufficient funds. Please insert an additional
            \(coinsNeeded) coins.&quot;)
} catch {
    print(&quot;Unexpected error: \(error).&quot;)
}
// Prints &quot;Insufficient funds. Please insert an additional 2 coins.&quot;
</pre></div>

<p>In the above example, the &lsquo;<samp>buyFavoriteSnack(person:vendingMachine:)</samp>&rsquo;
function is called in a &lsquo;<samp>try</samp>&rsquo; expression, because it can throw an error.
If an error is thrown, execution immediately transfers to the &lsquo;<samp>catch</samp>&rsquo;
clauses, which decide whether to allow propagation to continue. If no
pattern is matched, the error gets caught by the final &lsquo;<samp>catch</samp>&rsquo; clause
and is bound to a local &lsquo;<samp>error</samp>&rsquo; constant. If no error is thrown, the
remaining statements in the &lsquo;<samp>do</samp>&rsquo; statement are executed.
</p>
<p>The &lsquo;<samp>catch</samp>&rsquo; clauses don&rsquo;t have to handle every possible error that the
code in the &lsquo;<samp>do</samp>&rsquo; clause can throw. If none of the &lsquo;<samp>catch</samp>&rsquo; clauses handle
the error, the error propagates to the surrounding scope. However, the
propagated error must be handled by <em>some</em> surrounding scope. In a
nonthrowing function, an enclosing &lsquo;<samp>do</samp>&rsquo;-&lsquo;<samp>catch</samp>&rsquo; clause must handle the
error. In a throwing function, either an enclosing &lsquo;<samp>do</samp>&rsquo;-&lsquo;<samp>catch</samp>&rsquo; clause
or the caller must handle the error. If the error propagates to the
top-level scope without being handled, you&rsquo;ll get a runtime error.
</p>
<p>For example, the above example can be written so any error that isn&rsquo;t a
&lsquo;<samp>VendingMachineError</samp>&rsquo; is instead caught by the calling function:
</p>
<div class="example">
<pre class="example">func nourish(with item: String) throws {
    do {
        try vendingMachine.vend(itemNamed: item)
    } catch is VendingMachineError {
        print(&quot;Invalid selection, out of stock, or not enough money.&quot;)
    }
}

do {
    try nourish(with: &quot;Beet-Flavored Chips&quot;)
} catch {
    print(&quot;Unexpected non-vending-machine-related error: \(error)&quot;)
}
// Prints &quot;Invalid selection, out of stock, or not enough money.&quot;
</pre></div>

<p>In the &lsquo;<samp>nourish(with:)</samp>&rsquo; function, if &lsquo;<samp>vend(itemNamed:)</samp>&rsquo; throws an error
that&rsquo;s one of the cases of the &lsquo;<samp>VendingMachineError</samp>&rsquo; enumeration,
&lsquo;<samp>nourish(with:)</samp>&rsquo; handles the error by printing a message. Otherwise,
&lsquo;<samp>nourish(with:)</samp>&rsquo; propagates the error to its call site. The error is
then caught by the general &lsquo;<samp>catch</samp>&rsquo; clause.
</p>
<hr>
<div class="header">
<p>
Next: <a href="Converting-Errors-to-Optional-Values.html#Converting-Errors-to-Optional-Values" accesskey="n" rel="next">Converting Errors to Optional Values</a>, Previous: <a href="Propagating-Errors-Using-Throwing-Functions.html#Propagating-Errors-Using-Throwing-Functions" accesskey="p" rel="prev">Propagating Errors Using Throwing Functions</a>, Up: <a href="Handling-Errors.html#Handling-Errors" accesskey="u" rel="up">Handling Errors</a> &nbsp; [<a href="index.html#SEC_Contents" title="Table of contents" rel="contents">Contents</a>][<a href="Index.html#Index" title="Index" rel="index">Index</a>]</p>
</div>



</body>
</html>
