<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Created by GNU Texinfo 6.6, http://www.gnu.org/software/texinfo/ -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Propagating Errors Using Throwing Functions (The Swift Programming Language Guide (Swift 5.1))</title>

<meta name="description" content="Propagating Errors Using Throwing Functions (The Swift Programming Language Guide (Swift 5.1))">
<meta name="keywords" content="Propagating Errors Using Throwing Functions (The Swift Programming Language Guide (Swift 5.1))">
<meta name="resource-type" content="document">
<meta name="distribution" content="global">
<meta name="Generator" content="makeinfo">
<link href="index.html#Top" rel="start" title="Top">
<link href="Index.html#Index" rel="index" title="Index">
<link href="index.html#SEC_Contents" rel="contents" title="Table of Contents">
<link href="Handling-Errors.html#Handling-Errors" rel="up" title="Handling Errors">
<link href="Handling-Errors-Using-Do_002dCatch.html#Handling-Errors-Using-Do_002dCatch" rel="next" title="Handling Errors Using Do-Catch">
<link href="Handling-Errors.html#Handling-Errors" rel="prev" title="Handling Errors">
<style type="text/css">
<!--
a.summary-letter {text-decoration: none}
blockquote.indentedblock {margin-right: 0em}
div.display {margin-left: 3.2em}
div.example {margin-left: 3.2em}
div.lisp {margin-left: 3.2em}
kbd {font-style: oblique}
pre.display {font-family: inherit}
pre.format {font-family: inherit}
pre.menu-comment {font-family: serif}
pre.menu-preformatted {font-family: serif}
span.nolinebreak {white-space: nowrap}
span.roman {font-family: initial; font-weight: normal}
span.sansserif {font-family: sans-serif; font-weight: normal}
ul.no-bullet {list-style: none}
-->
</style>
<link rel="stylesheet" type="text/css" href="https://gnu.org/software/emacs/manual.css">


</head>

<body lang="en">
<span id="Propagating-Errors-Using-Throwing-Functions"></span><div class="header">
<p>
Next: <a href="Handling-Errors-Using-Do_002dCatch.html#Handling-Errors-Using-Do_002dCatch" accesskey="n" rel="next">Handling Errors Using Do-Catch</a>, Up: <a href="Handling-Errors.html#Handling-Errors" accesskey="u" rel="up">Handling Errors</a> &nbsp; [<a href="index.html#SEC_Contents" title="Table of contents" rel="contents">Contents</a>][<a href="Index.html#Index" title="Index" rel="index">Index</a>]</p>
</div>
<hr>
<span id="Propagating-Errors-Using-Throwing-Functions-1"></span><h4 class="subsection">22.2.1 Propagating Errors Using Throwing Functions</h4>

<p>To indicate that a function, method, or initializer can throw an error,
you write the &lsquo;<samp>throws</samp>&rsquo; keyword in the function&rsquo;s declaration after its
parameters. A function marked with &lsquo;<samp>throws</samp>&rsquo; is called a <em>throwing
function</em>. If the function specifies a return type, you write the
&lsquo;<samp>throws</samp>&rsquo; keyword before the return arrow (&lsquo;<samp>-&gt;</samp>&rsquo;).
</p>
<div class="example">
<pre class="example">func canThrowErrors() throws -&gt; String

func cannotThrowErrors() -&gt; String
</pre></div>

<p>A throwing function propagates errors that are thrown inside of it to
the scope from which it&rsquo;s called.
</p>
<p>Note
</p>
<p>Only throwing functions can propagate errors. Any errors thrown inside a
nonthrowing function must be handled inside the function.
</p>
<p>In the example below, the &lsquo;<samp>VendingMachine</samp>&rsquo; class has a
&lsquo;<samp>vend(itemNamed:)</samp>&rsquo; method that throws an appropriate
&lsquo;<samp>VendingMachineError</samp>&rsquo; if the requested item is not available, is out of
stock, or has a cost that exceeds the current deposited amount:
</p>
<div class="example">
<pre class="example">struct Item {
    var price: Int
    var count: Int
}

class VendingMachine {
    var inventory = [
      &quot;Candy Bar&quot;: Item(price: 12, count: 7),
      &quot;Chips&quot;: Item(price: 10, count: 4),
      &quot;Pretzels&quot;: Item(price: 7, count: 11)
    ]
    var coinsDeposited = 0

    func vend(itemNamed name: String) throws {
        guard let item = inventory[name] else {
            throw VendingMachineError.invalidSelection
        }

        guard item.count &gt; 0 else {
            throw VendingMachineError.outOfStock
        }

        guard item.price &lt;= coinsDeposited else {
            throw VendingMachineError.insufficientFunds(coinsNeeded: item.price - coinsDeposited)
        }

        coinsDeposited -= item.price

        var newItem = item
        newItem.count -= 1
        inventory[name] = newItem

        print(&quot;Dispensing \(name)&quot;)
    }
}
</pre></div>

<p>The implementation of the &lsquo;<samp>vend(itemNamed:)</samp>&rsquo; method uses &lsquo;<samp>guard</samp>&rsquo;
statements to exit the method early and throw appropriate errors if any
of the requirements for purchasing a snack aren&rsquo;t met. Because a &lsquo;<samp>throw</samp>&rsquo;
statement immediately transfers program control, an item will be vended
only if all of these requirements are met.
</p>
<p>Because the &lsquo;<samp>vend(itemNamed:)</samp>&rsquo; method propagates any errors it throws,
any code that calls this method must either handle the errors&mdash;using a
&lsquo;<samp>do</samp>&rsquo;-&lsquo;<samp>catch</samp>&rsquo; statement, &lsquo;<samp>try?</samp>&rsquo;, or &lsquo;<samp>try!</samp>&rsquo;&mdash;or continue to propagate
them. For example, the &lsquo;<samp>buyFavoriteSnack(person:vendingMachine:)</samp>&rsquo; in the
example below is also a throwing function, and any errors that the
&lsquo;<samp>vend(itemNamed:)</samp>&rsquo; method throws will propagate up to the point where
the &lsquo;<samp>buyFavoriteSnack(person:vendingMachine:)</samp>&rsquo; function is called.
</p>
<div class="example">
<pre class="example">let favoriteSnacks = [
  &quot;Alice&quot;: &quot;Chips&quot;,
  &quot;Bob&quot;: &quot;Licorice&quot;,
  &quot;Eve&quot;: &quot;Pretzels&quot;,
]
func buyFavoriteSnack(person: String, vendingMachine: VendingMachine) throws {
    let snackName = favoriteSnacks[person] ?? &quot;Candy Bar&quot;
    try vendingMachine.vend(itemNamed: snackName)
}
</pre></div>

<p>In this example, the &lsquo;<samp>buyFavoriteSnack(person: vendingMachine:)</samp>&rsquo;
function looks up a given person&rsquo;s favorite snack and tries to buy it
for them by calling the &lsquo;<samp>vend(itemNamed:)</samp>&rsquo; method. Because the
&lsquo;<samp>vend(itemNamed:)</samp>&rsquo; method can throw an error, it&rsquo;s called with the &lsquo;<samp>try</samp>&rsquo;
keyword in front of it.
</p>
<p>Throwing initializers can propagate errors in the same way as throwing
functions. For example, the initializer for the &lsquo;<samp>PurchasedSnack</samp>&rsquo;
structure in the listing below calls a throwing function as part of the
initialization process, and it handles any errors that it encounters by
propagating them to its caller.
</p>
<div class="example">
<pre class="example">struct PurchasedSnack {
    let name: String
    init(name: String, vendingMachine: VendingMachine) throws {
        try vendingMachine.vend(itemNamed: name)
        self.name = name
    }
}
</pre></div>

<hr>
<div class="header">
<p>
Next: <a href="Handling-Errors-Using-Do_002dCatch.html#Handling-Errors-Using-Do_002dCatch" accesskey="n" rel="next">Handling Errors Using Do-Catch</a>, Up: <a href="Handling-Errors.html#Handling-Errors" accesskey="u" rel="up">Handling Errors</a> &nbsp; [<a href="index.html#SEC_Contents" title="Table of contents" rel="contents">Contents</a>][<a href="Index.html#Index" title="Index" rel="index">Index</a>]</p>
</div>



</body>
</html>
